version: '3.8'

services:
  notes:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      - SERVER_PORT=3000
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PORT=3306
      - DATABASE_PASSWORD=thangtran
      - DATABASE_NAME=test
    volumes:
      - ./:/app
    command: npm run debug

  db:
    image: mysql:5.7.22
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: thangtran
    restart: on-failure
    volumes:
      - ./data:/var/lib/mysql
    # volumes:
      # - ./database/test.sql:/docker-entrypoint-initdb.d/init.sql

    # volumes:
      # - mongodb:/data/db
      # - mongodb_config:/data/configdb
# volumes:
  # mongodb:
  # mongodb_config: